//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBasmProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int Id { get; set; }
        public Nullable<int> Order_id { get; set; }
        public Nullable<int> Assignment_id { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Order Order { get; set; }
    }
}
